### ISSUE TITLE
What if I want to login with Auncrated Google Account?

### ISSUE THREAD

**Issue by itady74** [TimEnglart/BlackBoard-Course-Downloader#16]
### We have to sing in with google account cause our student mail are based on it, so is there a way to login with google in this code or not?

**Comment by TimEnglart** [comment]
I doubt the current code will be able to use google accounts as a login. But if the mobile application for Blackboard works it may allow you to login using your account credentials as this program uses the endpoints provided by the app.

I probably wont be able to implement this myself as my University does not use google accounts and I am finishing up my degree so I wont have access to Blackboard for much longer.

Feel free to Fork and make a pull request if you figure out how to implement this login method.

**Comment by TimEnglart** [comment]
Hi @itady74,
Thanks to @davenewham and his PR #18 hopefully this issue is resolved. Feel free to comment if the issue still persists hopefully you can get the program running or comment on #19 so we can track login issues and make implementable issues accordingly

Please Take a look at: Issue #13's comments to see if this can also resolve any issues.
