### ISSUE TITLE
Following error message when logging in

### ISSUE THREAD

**Issue by ghost** [TimEnglart/BlackBoard-Course-Downloader#3]
Hi TimEnglart,

First of all, I would like to thank you for making this project open-source for anyone to use. I'm in exactly the same situation where I need to download my blackboard courses and this is definitely the solution for me, especially since I have been trying for a while to code my own but could never get it to work with my University's custom blackboard setup.

The only issue I have experienced so far, preventing me from using the program, is that when I perform the following steps an error message appears. I can't seem to modify the source code to fix it though :/ 

Input username : works fine
Input password : works fine
I type c to search, then put in Brunel (my uni)
I select option 1

Window displays my ID at the top then after 2 seconds this appears:

Traceback (most recent call last):
  File "main.py", line 267, in <module>
    handle_arguments()
  File "main.py", line 98, in handle_arguments
    return main(args)
  File "main.py", line 116, in main
    navigate(bbc)
  File "main.py", line 140, in navigate
    next_item = navigation(options=selected_item.courses(), attribute='name', sort=True, title='Course')
  File "main.py", line 225, in navigation
    options = sorted(options, key=lambda element: getattr(element, attribute))
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

If you could fix this issue for me I would be super greatful!

ChemicalNameOfTitin

**Comment by TimEnglart** [comment]
Thanks for making me aware of this issue. It appears this is occurring due to the program not being able to pull all your courses correctly. This may be due to the program attempting to contact blackboard endpoint for the built-in API in the wrong location or cannot access the API.

I'll look into what is occurring by making a debugging script so that I can see what is occurring on your end

**Comment by TimEnglart** [comment]
I have made a debug script called `debug.py`. When you have time would you be able to upload that _dump.json_ file produced in a zip so that i can review what is going wrong. Feel free to view it yourself to isolate the issue or to remove possibly sensitive data. (Course names, Usernames, User Ids, etc)

**Comment by ghost** [comment]
Hi TimEnglart,

Thank you for your reply and suggested action. I have completed it and zipped the dump.json file below:

[dump.zip](https://github.com/TimEnglart/BlackBoard-Course-Downloader/files/3317658/dump.zip)

ChemicalNameOfTitin

**Comment by TimEnglart** [comment]
Thanks for the response ChemicalNameOfTitin

I believe I have found the source of the issue. I have currently made it so that the script will attempt to get the courses via the `/learn/api/public/v2/courses/{courseId}` Endpoint but your learn server is on an older API version which hasn't implemented this endpoint.

I'll push a patch in the next few hours and hope that fixes the issue

Edit: Once the issue is resolved and you are able to see your courses by looking at the dump as well if you are planing on downloading all your course documents you may want to use the `--mass-download` argument as it appears you have quite a lot of courses. Sadly at the moment user submitted documents don't get downloaded,

Tim Englart

**Comment by TimEnglart** [comment]
Feel free to reopen this issue if the problem persists

**Comment by ghost** [comment]
No need, it works perfectly now, THANK YOU SO MUCH! :) :)

I have a slight alteration proposal to how the program runs, could we exchange emails so I can continue the conversation there instead of in this closed issue?

**Comment by TimEnglart** [comment]
Sure. Contact me at the email: tim.englart@my.jcu.edu.au

Just make sure I can tell its you ;)
